version: '3'
services:
  node-server:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - .:/app
    expose:
      - '8081'
    restart: always
  client-server:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ./client:/app
    ports:
      - '3000:3000'
    restart: always
  redis-server:
    image: redis
    ports:
      - '6379:6379'
    restart: always
  zookeeper-server:
    image: zookeeper
    restart: always
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/app
    depends_on:
      - node-server
    ports:
      - '4000:4000'
