apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: client-server
  name: client-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: client-server
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: client-server
    spec:
      containers:
        - image: client-server
          name: client-server
          ports:
            - containerPort: 3000
          resources: {}
          volumeMounts:
            - mountPath: /app/node_modules
              name: client-server-claim0
            - mountPath: /app
              name: client-server-claim1
      restartPolicy: Always
      volumes:
        - name: client-server-claim0
          persistentVolumeClaim:
            claimName: client-server-claim0
        - name: client-server-claim1
          persistentVolumeClaim:
            claimName: client-server-claim1
status: {}
