apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: node-server
  name: node-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: node-server
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: node-server
    spec:
      containers:
        - image: node-server
          name: node-server
          ports:
            - containerPort: 8081
          resources: {}
          volumeMounts:
            - mountPath: /app/node_modules
              name: node-server-claim0
            - mountPath: /app
              name: node-server-claim1
      restartPolicy: Always
      volumes:
        - name: node-server-claim0
          persistentVolumeClaim:
            claimName: node-server-claim0
        - name: node-server-claim1
          persistentVolumeClaim:
            claimName: node-server-claim1
status: {}
