apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: node-server
  name: node-server
spec:
  ports:
    - name: "8081"
      port: 8081
      targetPort: 8081
    - name: 8081-tcp
      port: 8081
      targetPort: 8081
  selector:
    io.kompose.service: node-server
status:
  loadBalancer: {}
